version: "3.9"

services:
  database:
    image: "postgres:14-alpine"
    container_name: fast_tags_db
    deploy:
        resources:
            limits:
              cpus: "0.25"
              memory: 512M
            reservations:
              cpus: "0.10"
              memory: 128M
    expose:
      - "5432"
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    env_file:
      - .env

  api:
    image: "ernesmancebo/fast-tags:latest"
    container_name: fast_tags_api
    restart: on-failure:5
    platform: linux/x86_64
    ports:
      - "${APP_UVICORN_PORT}:8080"
    env_file:
      - .env
    links:
      - database
    depends_on:
      - database
