version: "3.9"

services:
  database:
    image: "postgres:14-alpine"
    container_name: fast_tags_db
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    command: |
      bash -c 'while !</dev/tcp/db/${POSTGRES_DB_PORT}; do sleep 1; done; uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - .:/usr/src/app/
    platform: linux/x86_64
    env_file:
      - .env
    links:
      - database
    depends_on:
      - database
    ports:
      - 8002:8000

volumes:
  db-data:
