version: '3.9'

services:
  database:
    image: "postgres:14-alpine"
    container_name: fast_tags_db
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    env_file:
      - .env
