version: "3.9"

services:
  database:
    image: "postgres:14-alpine"
    container_name: fast_tags_db
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - default

  web:
    build: .
    command: |
      bash -c 'opentelemetry-instrument uvicorn api.main:app --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - .:/usr/src/app/
    platform: linux/x86_64
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=FastTags
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://signoz-otel-collector:4317
    env_file:
      - .env
    links:
      - database
    depends_on:
      - database
    ports:
      - 8002:8000
    networks:
      - otlm
      - default

volumes:
  db-data:


networks:
  otlm:
    external: true
    name: clickhouse-setup_default
