"""uses ForeingKey2

Revision ID: 78db935547c8
Revises: a70344428be8
Create Date: 2023-03-11 18:40:40.928020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78db935547c8'
down_revision = 'a70344428be8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tagged_links', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tagged_links', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tagged_links', type_='foreignkey')
    op.drop_column('tagged_links', 'owner_id')
    # ### end Alembic commands ###
