"""Revision with Array

Revision ID: 960ef814f8c5
Revises: 4e4ad3a7ca01
Create Date: 2023-03-11 18:32:15.505629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960ef814f8c5'
down_revision = '4e4ad3a7ca01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
