"""uses ForeingKey

Revision ID: a70344428be8
Revises: 960ef814f8c5
Create Date: 2023-03-11 18:37:33.281726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70344428be8'
down_revision = '960ef814f8c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
