name: Fast-Tags
run-name: Push @${{ github.ref_name }} by @${{ github.actor }}
on: [ push ]

env:
  PY_VERSION: "3.10.10"

jobs:
  integration:
    runs-on: ubuntu-22.04

    steps:
      # Code Checkout
      - uses: actions/checkout@v3
      # Adds python to runner
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          # Python version X processor architecture
          python-version:  ${{ env.PY_VERSION }}
          architecture: "x64"
          cache: "pip"

      - name: Display used Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
          if [ -f requirements.test.txt ]
          then
              pip-sync requirements.txt requirements.test.txt
          else
              pip-sync requirements.txt
          fi

      - name: Lint code with Flake8
        run: |
          flake8  ./api/ schemas.py
        continue-on-error: true

      - name: Test with PyTest
        run: pytest tests --doctest-modules --junitxml=junit/test-results-${{ env.PY_VERSION }}.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ env.PY_VERSION }}.xml
          path: junit/test-results-${{ env.PY_VERSION }}.xml
        if: ${{ always() }}
